/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.9-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "Controller.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void Controller_free_fields(struct Controller *this)
{
		vdmFree(this->m_Controller_numFields);
				vdmFree(this->m_Controller_hwi);
	}

static void Controller_free(struct Controller *this)
{
	--this->_Controller_refs;
	if (this->_Controller_refs < 1)
	{
		Controller_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z17fieldInitializer2EV()	{

TVP ret_1 = newInt(1)
;

return ret_1;
}



 static  TVP _Z17fieldInitializer1EV(ControllerCLASS this)	{

TVP ret_2 = newInt(1)
;

return ret_2;
}


/* Controller.vdmrt 10:9 */
 static  void _Z4stepEV(ControllerCLASS this)	{

TVP TmpVar1 = _Z2IOEV(NULL)
;

TVP TmpVar2 = _Z2IOEV(NULL)
;

TVP TmpVar3 = _Z2IOEV(NULL)
;

TVP TmpVar4 = _Z2IOEV(NULL)
;

TVP TmpVar5 = _Z2IOEV(NULL)
;

TVP TmpVar6 = _Z2IOEV(NULL)
;

TVP TmpVar7 = _Z2IOEV(NULL)
;

TVP TmpVar8 = _Z2IOEV(NULL)
;

TVP TmpVar9 = _Z2IOEV(NULL)
;

TVP TmpVar10 = _Z2IOEV(NULL)
;

TVP TmpVar11 = _Z2IOEV(NULL)
;

TVP TmpVar12 = _Z2IOEV(NULL)
;

TVP TmpVar13 = _Z2IOEV(NULL)
;
/* Controller.vdmrt 13:12 */
TVP embeding_1 = newSeqVarGC(17, NULL, newCharGC('\n', NULL), newCharGC('H', NULL), newCharGC('e', NULL), newCharGC('l', NULL), newCharGC('l', NULL), newCharGC('o', NULL), newCharGC(',', NULL), newCharGC(' ', NULL), newCharGC('D', NULL), newCharGC('E', NULL), newCharGC(' ', NULL), newCharGC('w', NULL), newCharGC('o', NULL), newCharGC('r', NULL), newCharGC('l', NULL), newCharGC('d', NULL), newCharGC('\n', NULL))
;
/* Controller.vdmrt 13:3 */
CALL_FUNC(IO, IO, TmpVar1, CLASS_IO__Z5printEU, embeding_1);
/* Controller.vdmrt 16:12 */
TVP embeding_2 = newSeqVarGC(6, NULL, newCharGC('m', NULL), newCharGC('b', NULL), newCharGC('p', NULL), newCharGC(' ', NULL), newCharGC('=', NULL), newCharGC(' ', NULL))
;
/* Controller.vdmrt 16:3 */
CALL_FUNC(IO, IO, TmpVar2, CLASS_IO__Z5printEU, embeding_2);
/* Controller.vdmrt 16:32 */
TVP embeding_3 = CALL_FUNC(BoolPort, BoolPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mbp), CLASS_BoolPort__Z8getValueEV)
;
/* Controller.vdmrt 16:23 */
CALL_FUNC(IO, IO, TmpVar3, CLASS_IO__Z5printEU, embeding_3);
/* Controller.vdmrt 16:62 */
TVP embeding_4 = newSeqVarGC(1, NULL, newCharGC('\n', NULL))
;
/* Controller.vdmrt 16:53 */
CALL_FUNC(IO, IO, TmpVar4, CLASS_IO__Z5printEU, embeding_4);
/* Controller.vdmrt 18:20 */
TVP embeding_5 = CALL_FUNC(BoolPort, BoolPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mbp), CLASS_BoolPort__Z8getValueEV)
;
/* Controller.vdmrt 18:3 */
CALL_FUNC(BoolPort, BoolPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), cbp), CLASS_BoolPort__Z8setValueEB, embeding_5);
/* Controller.vdmrt 21:12 */
TVP embeding_6 = newSeqVarGC(6, NULL, newCharGC('m', NULL), newCharGC('i', NULL), newCharGC('p', NULL), newCharGC(' ', NULL), newCharGC('=', NULL), newCharGC(' ', NULL))
;
/* Controller.vdmrt 21:3 */
CALL_FUNC(IO, IO, TmpVar5, CLASS_IO__Z5printEU, embeding_6);
/* Controller.vdmrt 21:32 */
TVP embeding_7 = CALL_FUNC(IntPort, IntPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mip), CLASS_IntPort__Z8getValueEV)
;
/* Controller.vdmrt 21:23 */
CALL_FUNC(IO, IO, TmpVar6, CLASS_IO__Z5printEU, embeding_7);
/* Controller.vdmrt 21:62 */
TVP embeding_8 = newSeqVarGC(1, NULL, newCharGC('\n', NULL))
;
/* Controller.vdmrt 21:53 */
CALL_FUNC(IO, IO, TmpVar7, CLASS_IO__Z5printEU, embeding_8);
/* Controller.vdmrt 23:20 */
TVP embeding_9 = CALL_FUNC(IntPort, IntPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mip), CLASS_IntPort__Z8getValueEV)
;
/* Controller.vdmrt 23:3 */
CALL_FUNC(IntPort, IntPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), cip), CLASS_IntPort__Z8setValueEI, embeding_9);
/* Controller.vdmrt 26:12 */
TVP embeding_10 = newSeqVarGC(6, NULL, newCharGC('m', NULL), newCharGC('r', NULL), newCharGC('p', NULL), newCharGC(' ', NULL), newCharGC('=', NULL), newCharGC(' ', NULL))
;
/* Controller.vdmrt 26:3 */
CALL_FUNC(IO, IO, TmpVar8, CLASS_IO__Z5printEU, embeding_10);
/* Controller.vdmrt 26:32 */
TVP embeding_11 = CALL_FUNC(RealPort, RealPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mrp), CLASS_RealPort__Z8getValueEV)
;
/* Controller.vdmrt 26:23 */
CALL_FUNC(IO, IO, TmpVar9, CLASS_IO__Z5printEU, embeding_11);
/* Controller.vdmrt 26:62 */
TVP embeding_12 = newSeqVarGC(1, NULL, newCharGC('\n', NULL))
;
/* Controller.vdmrt 26:53 */
CALL_FUNC(IO, IO, TmpVar10, CLASS_IO__Z5printEU, embeding_12);
/* Controller.vdmrt 28:20 */
TVP embeding_13 = CALL_FUNC(RealPort, RealPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), mrp), CLASS_RealPort__Z8getValueEV)
;
/* Controller.vdmrt 28:3 */
CALL_FUNC(RealPort, RealPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), crp), CLASS_RealPort__Z8setValueER, embeding_13);
/* Controller.vdmrt 31:12 */
TVP embeding_14 = newSeqVarGC(7, NULL, newCharGC('m', NULL), newCharGC('s', NULL), newCharGC('p', NULL), newCharGC(' ', NULL), newCharGC('=', NULL), newCharGC(' ', NULL), newCharGC('\"', NULL))
;
/* Controller.vdmrt 31:3 */
CALL_FUNC(IO, IO, TmpVar11, CLASS_IO__Z5printEU, embeding_14);
/* Controller.vdmrt 31:34 */
TVP embeding_15 = CALL_FUNC(StringPort, StringPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), msp), CLASS_StringPort__Z8getValueEV)
;
/* Controller.vdmrt 31:25 */
CALL_FUNC(IO, IO, TmpVar12, CLASS_IO__Z5printEU, embeding_15);
/* Controller.vdmrt 31:64 */
TVP embeding_16 = newSeqVarGC(2, NULL, newCharGC('\"', NULL), newCharGC('\n', NULL))
;
/* Controller.vdmrt 31:55 */
CALL_FUNC(IO, IO, TmpVar13, CLASS_IO__Z5printEU, embeding_16);
/* Controller.vdmrt 34:25 */
TVP embeding_17 = CALL_FUNC(StringPort, StringPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), msp), CLASS_StringPort__Z8getValueEV)
;
/* Controller.vdmrt 35:25 */
TVP embeding_18 = newSeqVarGC(0, NULL, NULL)
;
/* Controller.vdmrt 33:3 */
if ( toBool(vdmLessOrEqualGC(vdmSeqLenGC(CALL_FUNC(StringPort, StringPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), msp), CLASS_StringPort__Z8getValueEV), NULL), newIntGC(20, NULL), NULL)) )
	/* Controller.vdmrt 34:8 */
	CALL_FUNC(StringPort, StringPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), csp), CLASS_StringPort__Z8setValueE1QC, embeding_17);else
	/* Controller.vdmrt 35:8 */
	CALL_FUNC(StringPort, StringPort, GET_FIELD_GC(HardwareInterface, HardwareInterface, GET_FIELD_PTR_GC(Controller, Controller, this, hwi), csp), CLASS_StringPort__Z8setValueE1QC, embeding_18);;
}



 void Controller_const_init()	{

numFields_1 = _Z17fieldInitializer2EV();

return ;
}



 void Controller_const_shutdown()	{

vdmFree(numFields_1);

return ;
}



 void Controller_static_init()	{

return ;
}



 void Controller_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
/*  VTable for this class  */
 static  struct VTable VTableArrayForController  [] ={

{0,0,((VirtualFunctionPointer) _Z10ControllerE17CHardwareInterface),},
{0,0,((VirtualFunctionPointer) _Z4stepEV),},
{0,0,((VirtualFunctionPointer) _Z10ControllerEV),},
				
}  ;

/*  Overload VTables  */


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
ControllerCLASS Controller_Constructor(ControllerCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (ControllerCLASS) malloc(sizeof(struct Controller));
	}

	if(this_ptr!=NULL)
	{
	
			
		/*  Controller init  */
		this_ptr->_Controller_id = CLASS_ID_Controller_ID;
		this_ptr->_Controller_refs = 0;
		this_ptr->_Controller_pVTable=VTableArrayForController;

				this_ptr->m_Controller_numFields= _Z17fieldInitializer1EV(this_ptr);
									this_ptr->m_Controller_hwi= NULL ;
			}

	return this_ptr;
}

/*  Method for creating new "class"  */
static TVP new()
{
	ControllerCLASS ptr=Controller_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_Controller_id, &ptr->_Controller_refs, (freeVdmClassFunction)&Controller_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

    /* Controller.vdmrt 7:9 */
 TVP _Z10ControllerE17CHardwareInterface(ControllerCLASS this, TVP phwi)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, Controller);
}
;
/* Controller.vdmrt 8:30 */
TVP field_tmp_1 = vdmCloneGC(phwi, NULL)
;

SET_FIELD_PTR(Controller, Controller, this, hwi, field_tmp_1);

vdmFree(field_tmp_1);

return __buf;
}


    /* Controller.vdmrt 1:7 */
 TVP _Z10ControllerEV(ControllerCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, Controller);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
/*  initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order  */
		TVP numFields_1 =  NULL ;
		
