/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.9-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#include "HardwareInterface.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void HardwareInterface_free_fields(struct HardwareInterface *this)
{
		vdmFree(this->m_HardwareInterface_numFields);
				vdmFree(this->m_HardwareInterface_cbp);
			vdmFree(this->m_HardwareInterface_cip);
			vdmFree(this->m_HardwareInterface_crp);
			vdmFree(this->m_HardwareInterface_mbp);
			vdmFree(this->m_HardwareInterface_mip);
			vdmFree(this->m_HardwareInterface_mrp);
	}

static void HardwareInterface_free(struct HardwareInterface *this)
{
	--this->_HardwareInterface_refs;
	if (this->_HardwareInterface_refs < 1)
	{
		HardwareInterface_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z18fieldInitializer28EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 43:27 */
TVP ret_27 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_27;
}



 static  TVP _Z18fieldInitializer27EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 40:26 */
TVP ret_28 = _Z7IntPortEI(NULL, newInt(0))
;

return ret_28;
}



 static  TVP _Z18fieldInitializer26EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 37:27 */
TVP ret_29 = _Z8BoolPortEB(NULL, newBool(false))
;

return ret_29;
}



 static  TVP _Z18fieldInitializer25EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 29:27 */
TVP ret_30 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_30;
}



 static  TVP _Z18fieldInitializer24EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 26:26 */
TVP ret_31 = _Z7IntPortEI(NULL, newInt(0))
;

return ret_31;
}



 static  TVP _Z18fieldInitializer23EV(HardwareInterfaceCLASS this)	{
/* HardwareInterface.vdmrt 23:27 */
TVP ret_32 = _Z8BoolPortEB(NULL, newBool(false))
;

return ret_32;
}



 static  TVP _Z18fieldInitializer22EV()	{

TVP ret_33 = newInt(6)
;

return ret_33;
}



 static  TVP _Z18fieldInitializer21EV(HardwareInterfaceCLASS this)	{

TVP ret_34 = newInt(6)
;

return ret_34;
}



 void HardwareInterface_const_init()	{

numFields_6 = _Z18fieldInitializer22EV();

return ;
}



 void HardwareInterface_const_shutdown()	{

vdmFree(numFields_6);

return ;
}



 void HardwareInterface_static_init()	{

return ;
}



 void HardwareInterface_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
/*  VTable for this class  */
 static  struct VTable VTableArrayForHardwareInterface  [] ={

{0,0,((VirtualFunctionPointer) _Z17HardwareInterfaceEV),},
				
}  ;

/*  Overload VTables  */


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
HardwareInterfaceCLASS HardwareInterface_Constructor(HardwareInterfaceCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (HardwareInterfaceCLASS) malloc(sizeof(struct HardwareInterface));
	}

	if(this_ptr!=NULL)
	{
	
			
		/*  HardwareInterface init  */
		this_ptr->_HardwareInterface_id = CLASS_ID_HardwareInterface_ID;
		this_ptr->_HardwareInterface_refs = 0;
		this_ptr->_HardwareInterface_pVTable=VTableArrayForHardwareInterface;

				this_ptr->m_HardwareInterface_numFields= _Z18fieldInitializer21EV(this_ptr);
									this_ptr->m_HardwareInterface_cbp= _Z18fieldInitializer23EV(this_ptr);
						this_ptr->m_HardwareInterface_cip= _Z18fieldInitializer24EV(this_ptr);
						this_ptr->m_HardwareInterface_crp= _Z18fieldInitializer25EV(this_ptr);
						this_ptr->m_HardwareInterface_mbp= _Z18fieldInitializer26EV(this_ptr);
						this_ptr->m_HardwareInterface_mip= _Z18fieldInitializer27EV(this_ptr);
						this_ptr->m_HardwareInterface_mrp= _Z18fieldInitializer28EV(this_ptr);
			}

	return this_ptr;
}

/*  Method for creating new "class"  */
static TVP new()
{
	HardwareInterfaceCLASS ptr=HardwareInterface_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_HardwareInterface_id, &ptr->_HardwareInterface_refs, (freeVdmClassFunction)&HardwareInterface_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

    /* HardwareInterface.vdmrt 15:7 */
 TVP _Z17HardwareInterfaceEV(HardwareInterfaceCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, HardwareInterface);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
/*  initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order  */
		TVP numFields_6 =  NULL ;
							
