/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.9-SNAPSHOT.
* Website: https://github.com/overturetool/vdm2c
*/

#ifndef CLASSES_HardwareInterface_H_
#define CLASSES_HardwareInterface_H_

#define VDM_CG

#include "Vdm.h"

/*  include types used in the class */
#include "IntPort.h"
#include "HardwareInterface.h"
#include "BoolPort.h"
#include "RealPort.h"


/* -------------------------------
 *
 * Quotes
 *
 --------------------------------- */ 
 


/* -------------------------------
 *
 * values / global const
 *
 --------------------------------- */ 
 
extern TVP numFields_6;


/* -------------------------------
 *
 * The class
 *
 --------------------------------- */ 
 

/*  class id  */
#define CLASS_ID_HardwareInterface_ID 9

#define HardwareInterfaceCLASS struct HardwareInterface*

/*  The vtable ids  */
#define CLASS_HardwareInterface__Z17HardwareInterfaceEV 0

struct HardwareInterface
{
	
/* Definition of Class: 'HardwareInterface' */
	VDM_CLASS_BASE_DEFINITIONS(HardwareInterface);
	 
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,numFields);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,cbp);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,cip);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,crp);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,mbp);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,mip);
	VDM_CLASS_FIELD_DEFINITION(HardwareInterface,mrp);
	
};


/* -------------------------------
 *
 * Constructors
 *
 --------------------------------- */ 
 
  
  	/* HardwareInterface.vdmrt 15:7 */
	TVP _Z17HardwareInterfaceEV(HardwareInterfaceCLASS this_); 


/* -------------------------------
 *
 * public access functions
 *
 --------------------------------- */ 
 
	void HardwareInterface_const_init();
	void HardwareInterface_const_shutdown();
	void HardwareInterface_static_init();
	void HardwareInterface_static_shutdown();


/* -------------------------------
 *
 * Internal
 *
 --------------------------------- */ 
 

void HardwareInterface_free_fields(HardwareInterfaceCLASS);
HardwareInterfaceCLASS HardwareInterface_Constructor(HardwareInterfaceCLASS);



#endif /* CLASSES_HardwareInterface_H_ */
